# Add your Supabase credentials here
# You can find these in your Supabase Dashboard under Settings > API

SUPABASE_URL = "https://exlenoctpysjwgkusxfh.supabase.co"
SUPABASE_KEY = "sb_publishable_W46D0Hn2TI3Xhgc69eVRNw_BDTYFItb"
